#!/usr/bin/env bash
set -ex

DATE=$(date +"%d-%m-%Y-%H_%M_%S")
# http://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself
exec > >(tee -i /tmp/log-wp-${DATE}.txt)
date
echo "Info: This log was generated by running a script"

useradd ${ssh_guestadmin_username} 
usermod -aG wheel ${ssh_guestadmin_username} 

echo ${ssh_guestadmin_password} | passwd --stdin ${ssh_guestadmin_username} 
echo 'guestadmin  ALL=(ALL)       NOPASSWD: ALL' > /etc/sudoers.d/guestadmin

sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
systemctl restart sshd
