#!/usr/bin/env bash
set -ex

DATE=$(date +"%d-%m-%Y-%H_%M_%S")
# http://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself
exec > >(tee -i /tmp/log-wp-${DATE}.txt)
date
echo "Info: This log was generated by running a script"

mkdir /root/downloads  || exit 1
cd /root/downloads || exit 1
curl -L ${dropbox_folder_link} > /root/downloads/download.zip || exit 1
unzip download.zip -x / || exit 1
rm download.zip || exit 1

chown -R apache:apache /root/downloads   || exit 1

cd /root/downloads/premium-plugins/backupbuddy || exit 1

cp backup-codingbee_net* /var/www/html/ || exit 1
cp importbuddy.php /var/www/html/ || exit 1

chown -R apache:apache /var/www/html/ || exit 1

systemctl restart httpd  || exit 1


exit 0
